version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: reportes_postgres
    restart: always
    environment:
      POSTGRES_DB: reportes_db
      POSTGRES_USER: reportes_user
      POSTGRES_PASSWORD: reportes_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
