spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/reportes_db
    username: reportes_user
    password: reportes_pass
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: playcanada513@gmail.com
    password: rhjx vhfj svdu medl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/reportes-backend.log
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      simple:
        enabled: true
jwt:
  secret: "cambia_esto_por_un_secreto_muy_seguro"
  expiration: 86400000 # 1 día en ms
