spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/reportes_db
    username: reportes_user
    password: reportes_pass
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail_user@gmail.com
    password: your_gmail_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: WARN
  file:
    name: logs/reportes-backend.log
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    export:
      simple:
        enabled: true
jwt:
  secret: "cambia_esto_por_un_secreto_prod"
  expiration: 86400000
